name: Node.js CI

on: push

jobs:
    build-engine:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Clean install
              working-directory: projects/feather-engine-core
              run: npm ci
            - name: Build
              working-directory: projects/feather-engine-core
              run: npm run build --if-present
            - name: Test
              working-directory: projects/feather-engine-core
              run: npm test
            - name: Store built module
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Store coverage information
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-core-coverage
                  path: projects/feather-engine-core/coverage

    build:
        runs-on: ubuntu-latest
        needs: build-engine
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Download a feather-engine-core
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Download a feather-engine-core/coverage
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core-coverage
                  path: projects/feather-engine-core/coverage
            - run: ls -la
            - name: in fec
              run: ls -la
              working-directory: projects/feather-engine-core

            - name: Clean install
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Test
              run: npm test
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
