name: Node.js CI

on: push

jobs:
    build-engine-events:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Clean install
              working-directory: projects/feather-engine-events
              run: npm ci
            - name: Build
              working-directory: projects/feather-engine-events
              run: npm run build --if-present
            - name: Test
              working-directory: projects/feather-engine-events
              run: npm test
            - name: Store built module
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-events
                  path: projects/feather-engine-events/dist
            - name: Store coverage information
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-events-coverage
                  path: projects/feather-engine-events/coverage
    build-engine-core:
        runs-on: ubuntu-latest
        needs: [build-engine-events]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Download a feather-engine-events
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-events
                  path: projects/feather-engine-events/dist
            - name: Clean install
              working-directory: projects/feather-engine-core
              run: npm ci
            - name: Build
              working-directory: projects/feather-engine-core
              run: npm run build --if-present
            - name: Test
              working-directory: projects/feather-engine-core
              run: npm test
            - name: Store built module
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Store coverage information
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-core-coverage
                  path: projects/feather-engine-core/coverage
    build-engine-entities:
        runs-on: ubuntu-latest
        needs: [build-engine-events, build-engine-core, build-engine-graphics]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Download a feather-engine-core
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Download a feather-engine-events
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-events
                  path: projects/feather-engine-events/dist
            - name: Download a feather-engine-graphics
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-graphics
                  path: projects/feather-engine-graphics/dist
            - name: Clean install core
              working-directory: projects/feather-engine-core
              run: npm ci
            - name: Clean install graphics
              working-directory: projects/feather-engine-graphics
              run: npm ci
            - name: Clean install
              working-directory: projects/feather-engine-entities
              run: npm ci
            - name: Build
              working-directory: projects/feather-engine-entities
              run: npm run build --if-present
            - name: Test
              working-directory: projects/feather-engine-entities
              run: npm test
            - name: Store built module
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-entities
                  path: projects/feather-engine-entities/dist
            - name: Store coverage information
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-entities-coverage
                  path: projects/feather-engine-entities/coverage
    build-engine-graphics:
        runs-on: ubuntu-latest
        needs: [build-engine-core, build-engine-events]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Download a feather-engine-core
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Download a feather-engine-events
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-events
                  path: projects/feather-engine-events/dist
            - name: Clean install core
              working-directory: projects/feather-engine-core
              run: npm ci
            - name: Clean install
              working-directory: projects/feather-engine-graphics
              run: npm ci
            - name: Build
              working-directory: projects/feather-engine-graphics
              run: npm run build --if-present
            - name: Test
              working-directory: projects/feather-engine-graphics
              run: npm test
            - name: Store built module
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-graphics
                  path: projects/feather-engine-graphics/dist
            - name: Store coverage information
              uses: actions/upload-artifact@v2
              with:
                  name: feather-engine-graphics-coverage
                  path: projects/feather-engine-graphics/coverage

    build:
        runs-on: ubuntu-latest
        needs: [build-engine-core, build-engine-graphics, build-engine-events, build-engine-entities]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Download a feather-engine-core
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core
                  path: projects/feather-engine-core/dist
            - name: Download a feather-engine-core/coverage
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-core-coverage
                  path: projects/feather-engine-core/coverage
            - name: Download a feather-engine-events/coverage
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-events-coverage
                  path: projects/feather-engine-events/coverage
            - name: Download a feather-engine-entities/coverage
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-entities-coverage
                  path: projects/feather-engine-entities/coverage
            - name: Download a feather-engine-graphics
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-graphics
                  path: projects/feather-engine-graphics/dist
            - name: Download a feather-engine-graphics/coverage
              uses: actions/download-artifact@v2
              with:
                  name: feather-engine-graphics-coverage
                  path: projects/feather-engine-graphics/coverage
            - name: Clean install events
              working-directory: projects/feather-engine-events
              run: npm ci
            - name: Clean install core
              working-directory: projects/feather-engine-core
              run: npm ci
            - name: Clean install graphics
              working-directory: projects/feather-engine-graphics
              run: npm ci
            - name: Clean install entities
              working-directory: projects/feather-engine-entities
              run: npm ci
            - name: Clean install entities
              working-directory: projects/feather-engine-entities
              run: npm ci
            - name: Clean install
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Test
              run: npm test
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
